### ISSUE TITLE
organisatie 2022

### ISSUE THREAD

**Issue by Caber-nl** [ScoutingRudyardKipling/BlackJackClient#108]
Hoi Frank (en anderen),

Zouden we in contact kunnen komen over deze app? Mogelijk kunnen wij hem ook gebruiken voor de BlackJack 2022?

blackjack@scoutingstratum.nl

**Comment by frankkuipers** [comment]
Ja hoor, helemaal goed! Jullie kunnen me tzt bereiken op frank@rudyardkipling.nl . Als jullie iemand met de technische kennis hebben, dan mag je ook aanpassingen doen aan de broncode om alles goed op jullie blackjack aan te laten sluiten
